### ISSUE TITLE
Use gitlab instead of node-gitlab-api

### ISSUE THREAD

**Issue by SBI-** [jazz-community/rtc-git-connector#17]
The `node-gitlab-api` npm package has been deprecated in favor of just `gitlab`. [This issue](https://github.com/jdalrymple/node-gitlab/issues/78) is used to track progress of moving all references to the new library, deprecating the old one of that name.

**Comment by SBI-** [comment]
- Using the jazz proxy as we have previously doesn't work reliably anymore
- All API calls in our code need to be adjusted to use the new API structure

It's quite possible that I haven't found some issues concerning usage of the release.

**Comment by MartinBenninger** [comment]
- We have determined that the jazz proxy wasn't needed and so it has been removed.
- The API has also been updated and the code adjusted accordingly.

All fixes done in merge request #21
