### ISSUE TITLE
Update README to reflect latest changes

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-git-connector#26]
With a recent release, the UI has been overhauled and is now much cleaner. The README should be updated with new screen shots and feature description to meet the current implementation status

**Comment by MartinBenninger** [comment]
@innerjoin Please take a look at the new [Wiki](https://github.com/jazz-community/rtc-git-connector/wiki). It contains the latest documentation and screenshots.

I've also reduced the size of the readme now that the information is in the Wiki pages.

@innerjoin and @SBI- I'd be glad for any feedback on both the new wiki and the updated readme. Thanks!

**Comment by innerjoin** [comment]
@MartinBenninger Awesome, thanks a lot!

A few points:
- Chapter 4 (Contributing) and 5 (Licensing) are now duplicated in the README and wiki. I would remove those chapters in the wiki
- I would move the sentence `This project contains detailed documentation and instructions in the Wiki.` in the README to a separate section named 'Documentation' or 'Installation & Usage' to make sure that it is not over-read.

**Comment by MartinBenninger** [comment]
@innerjoin Good points, I agree.

I've made the changes and will now close this issue.
