### ISSUE TITLE
Update the RTC Git Connector Wiki on GitHub

### ISSUE THREAD

**Issue by MartinBenninger** [jazz-community/rtc-git-connector#31]
### Description

- Add screenshots and a description for all the new features released in the latest version (user documentation).  
  
- Add instructions for using the new theme files (admin documentation).

### Other Attributes

| Attributes | Values |
| --- | --- |
| Owned By | [Benninger, Martin, ZUG](mailto:martin.benninger@siemens.com) |
| Filed Against | RTC GIT Integration Package |
| Planned For | 2018.09 |
| Tags | documentation |

**Comment by MartinBenninger** [comment]
This issue was linked by [RTC Work Item 681763](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/681763) on behalf of martin.benninger@siemens.com

**Comment by MartinBenninger** [comment]
I updated the wiki with the following two pages:
- [Creating Work Items from Git Issues](https://github.com/jazz-community/rtc-git-connector/wiki/2.10-Creating-Work-Items)
- [Custom Theme](https://github.com/jazz-community/rtc-git-connector/wiki/3.6-Custom-Theme)

**Comment by innerjoin** [comment]
Great work, thanks a lot
