### ISSUE TITLE
Upgrade packages

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-git-connector#33]
There are some older packages used of which one has a security flaw. Upgrade all packages to the latest version, especially the `gitlab` package

**Comment by MartinBenninger** [comment]
This issue was linked by [RTC Work Item 746010](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/746010) on behalf of martin.benninger@siemens.com

**Comment by MartinBenninger** [comment]
This issue was linked by [RTC Work Item 749727](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/749727) on behalf of martin.benninger@siemens.com
