### ISSUE TITLE
Consider exchanging the ZIP library

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-git-connector#39]
We are currently using `gzip-js` in this project, which itself depends on `deflate-js`. _deflate-js_ has a problematic GPL V2 only license and might therefore cause inconsistencies when we declare our project as _MIT_.

**Comment by MartinBenninger** [comment]
This issue was linked by [RTC Work Item 758045](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/758045) on behalf of martin.benninger@siemens.com
