### ISSUE TITLE
Does this connector require RTC Git Integration Toolkit?

### ISSUE THREAD

**Issue by mahmad123** [jazz-community/rtc-git-connector#48]

**Comment by mahmad123** [comment]
In the terrrible RTC documentation, it says that you to support *Server Side Hooks*, you will need to install the **RTC Git Integration Toolkit**.  But if we are using GitLab.com, not a self-hosted instance, we cannot do this.

**Comment by SBI-** [comment]
[Git Connector](https://github.com/jazz-community/rtc-git-connector) and [Git Connector Service](https://github.com/jazz-community/rtc-git-connector) do not require the Git Integration Toolkit to run. All necessary information is requested on demand. This is also the reason for storing access tokens.
